<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Types.cs" Link="Types.cs" />
    <Compile Include="..\KakuroParser.cs" Link="KakuroParser.cs" />
    <Compile Include="..\HumanSolver.cs" Link="HumanSolver.cs" />
  </ItemGroup>

</Project>